"""add deadline and status

Revision ID: 3e9e8c3631fa
Revises: 34eeaf80e863
Create Date: 2026-06-15 22:42:22.955755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9e8c3631fa'
down_revision = '34eeaf80e863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='under_review'))

    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.drop_column('deadline')

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
