"""add_supplier_profile_fields

Revision ID: 7123103ee716
Revises: c00a928eda1c
Create Date: 2026-06-19 22:30:48.779868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7123103ee716'
down_revision = 'c00a928eda1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('registration_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('registration_number')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
