"""add_red_flags_to_proposals

Revision ID: c00a928eda1c
Revises: daf38233124d
Create Date: 2026-06-18 01:39:14.866994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00a928eda1c'
down_revision = 'daf38233124d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('red_flags', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_column('red_flags')

    # ### end Alembic commands ###
