"""add llm_verdict to proposal_requirements

Revision ID: daf38233124d
Revises: 31ccabafb0f5
Create Date: 2026-06-18 01:32:08.653482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf38233124d'
down_revision = '31ccabafb0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_verdict', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal_requirements', schema=None) as batch_op:
        batch_op.drop_column('llm_verdict')

    # ### end Alembic commands ###
